/* Datos de EJEMPLO (tus autos de Instagram). Se ignoran al conectar tu planilla en js/config.js. Borrable. */
window.STOCK_DEMO = [
    {
        "id":  "001",
        "marca":  "Peugeot",
        "modelo":  "208",
        "version":  "Full Techo Panorámico",
        "anio":  "2014",
        "km":  85000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nPEUGEOT 208 UNICO DUEÑO EL MAS FULL CON TECHO PANORÁMICO 85 MIL KM!\n\n- AIRE ACONDICIONADO\n- TECHO DE VIDRIO PANORÁMICO \n- DIRECCIÓN HIDRÁULICA\n- FAROS CAMINEROS \n- MOTOR 1.2 AÑO 2014\n- RADIO CON PANTALLA\n- ESPEJOS ELÉCTRICOS\n- COMPUTADORA DE ABORDO\n- VIDRIOS ELÉCTRICOS\n- CIERRE CENTRALIZADO \n- LLANTAS DE ALEACIÓN 15\"\n- COMANDOS AL VOLANTE\n- 85.000KM!\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN PROPIA ENTREGANDO DESDE US$8000 Y CUOTAS ⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO\n📲 096 187 061",
        "fotos":  [
                      "img/autos/001/1.jpg",
                      "img/autos/001/2.jpg",
                      "img/autos/001/3.jpg",
                      "img/autos/001/4.jpg",
                      "img/autos/001/5.jpg",
                      "img/autos/001/6.jpg",
                      "img/autos/001/7.jpg",
                      "img/autos/001/8.jpg"
                  ],
        "destacado":  true
    },
    {
        "id":  "002",
        "marca":  "Renault",
        "modelo":  "Kwid",
        "version":  "Outsider",
        "anio":  "2020",
        "km":  67000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nRENAULT KWID OUTSIDER 2020 EXTRA FULL 1.0 SUPER ECONÓMICO 67.000KM! \n\n- PANTALLA Y CÁMARA DE REVERSA \n- 4 AIRBAGS\n- AIRE ACONDICIONADO \n- DIRECCIÓN HIDRÁULICA \n- VIDRIOS ELÉCTRICOS \n- CIERRE CENTRALIZADO\n- 1.0 SUPER ECONÓMICO!\n- 2020\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS⚠️\n\n⚠️O FINANCIACIÓN ENTREGANDO DESDE US$8000⚠️ \n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO\n📲 096 187 061",
        "fotos":  [
                      "img/autos/002/1.jpg",
                      "img/autos/002/2.jpg",
                      "img/autos/002/3.jpg",
                      "img/autos/002/4.jpg",
                      "img/autos/002/5.jpg",
                      "img/autos/002/6.jpg",
                      "img/autos/002/7.jpg",
                      "img/autos/002/8.jpg"
                  ],
        "destacado":  true
    },
    {
        "id":  "003",
        "marca":  "Nissan",
        "modelo":  "Kicks",
        "version":  "Advance",
        "anio":  "2019",
        "km":  89000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nNISSAN KICKS ADVANCE 2019 VERSION EXTRA FULL \n\n- EXTRA FULL \n- AIRE ACONDICIONADO \n- DIRECCIÓN HIDRÁULICA \n- FAROS CAMINEROS \n- ESPEJOS ELÉCTRICOS\n- COMPUTADORA DE ABORDO\n- VIDRIOS ELÉCTRICOS \n- AIRBAGS\n- COMANDO AL VOLANTE\n- CIERRE CENTRALIZADO \n- LLANTAS DE ALEACIÓN \n- 2019\n- 1.6 SUPER ECONÓMICA\n- 89.000KM\n\n🏁LLÉVALA CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN PROPIA ENTREGANDO DESDE US$10000 Y EL RESTO A 24 CUOTAS ⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO \n📲 096 187 061",
        "fotos":  [
                      "img/autos/003/1.jpg",
                      "img/autos/003/2.jpg",
                      "img/autos/003/3.jpg",
                      "img/autos/003/4.jpg",
                      "img/autos/003/5.jpg",
                      "img/autos/003/6.jpg",
                      "img/autos/003/7.jpg",
                      "img/autos/003/8.jpg",
                      "img/autos/003/9.jpg"
                  ],
        "destacado":  true
    },
    {
        "id":  "004",
        "marca":  "Chevrolet",
        "modelo":  "Celta",
        "version":  "Hatch",
        "anio":  "2006",
        "km":  171000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️NUEVO INGRESO⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nCHEVROLET CELTA HATCH 4 PUERTAS 1.0 SUPER ECONÓMICO\n\n- 1.0 SUPER ECONOMICO\n- 2006\n- 171 MIL KM!\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓNENTREGANDO US$4500 Y EL RESTO CUOTAS⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO \n📲 096 187 061",
        "fotos":  [
                      "img/autos/004/1.jpg",
                      "img/autos/004/2.jpg",
                      "img/autos/004/3.jpg",
                      "img/autos/004/4.jpg",
                      "img/autos/004/5.jpg",
                      "img/autos/004/6.jpg",
                      "img/autos/004/7.jpg",
                      "img/autos/004/8.jpg",
                      "img/autos/004/9.jpg"
                  ],
        "destacado":  true
    },
    {
        "id":  "005",
        "marca":  "Fiat",
        "modelo":  "Strada",
        "version":  "Working Doble Cabina",
        "anio":  "2014",
        "km":  "",
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO⚠️ \n\nVENDO - PERMUTO - FINANCIO\n\nFIAT STRADA WORKING DOBLE CABINA 2014 3 PUERTAS 1.4 FULL!!\n\n- DOBLE CABINA 3 PUERTAS\n- VIDRIOS ELÉCTRICOS \n- AIRE ACONDICIONADO\n- DIRECCIÓN HIDRÁULICA \n- RADIO CON USB\n- MOTOR 1.4\n- 2014\n\n🏁LLÉVALA CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN ENTREGANDO DESDE US$8000 Y CUOTAS ⚠️",
        "fotos":  [
                      "img/autos/005/1.jpg",
                      "img/autos/005/2.jpg",
                      "img/autos/005/3.jpg",
                      "img/autos/005/4.jpg",
                      "img/autos/005/5.jpg",
                      "img/autos/005/6.jpg",
                      "img/autos/005/7.jpg",
                      "img/autos/005/8.jpg"
                  ],
        "destacado":  true
    },
    {
        "id":  "006",
        "marca":  "Chevrolet",
        "modelo":  "Onix",
        "version":  "Joy",
        "anio":  "2023",
        "km":  64000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nCHEVROLET ONIX JOY 2023 1.0 CAJA 6TA (CORREA NO BAÑADA) SUPER ECONÓMICO CON PANTALLA\n\n- AIRE ACONDICIONADO\n- PANTALLA\n- 1.0 CAJA 6TA SUPER ECONÓMICO\n- DIRECCIÓN HIDRÁULICA \n- VIDRIOS ELÉCTRICOS \n- AIRBAG\n- CIERRE CENTRALIZADO \n- SUPER ECONÓMICO! \n- 64.000km\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBONDE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN ENTREGANDO DESDE US$8000 Y EL ES RESTO EN CUOTAS ⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO\n📲 096 187 061",
        "fotos":  [
                      "img/autos/006/1.jpg",
                      "img/autos/006/2.jpg",
                      "img/autos/006/3.jpg",
                      "img/autos/006/4.jpg",
                      "img/autos/006/5.jpg",
                      "img/autos/006/6.jpg",
                      "img/autos/006/7.jpg",
                      "img/autos/006/8.jpg",
                      "img/autos/006/9.jpg",
                      "img/autos/006/10.jpg"
                  ],
        "destacado":  true
    },
    {
        "id":  "007",
        "marca":  "Nissan",
        "modelo":  "Versa",
        "version":  "Exclusive",
        "anio":  "2021",
        "km":  88000,
        "combustible":  "Nafta",
        "caja":  "Automática",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nNISSAN NEW VERSA EXCLUSIVE AUTOMATICO 2021 1.6 SOLO 88 MIL KM!! EL MAS FULL CON CUERO\n\n- AIRE ACONDICIONADO \n- ASIENTOS DE CUERO\n- DIRECCIÓN HIDRÁULICA\n- CAMARA MARCHA ATRAS\n- COMANDOS AL VOLANTE \n- VIDRIOS ELÉCTRICOS \n- DOBLE AIRBAG\n- VELOCIDAD CRUCERO\n- COMPUTADORA DE ABORDO\n- LLANTAS\n- FAROS CAMINEROS\n- CIERRE CENTRALIZADO \n- 2021\n- SOLO 88.000 KMS\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN PROPIA ENTREGANDO DESDE US$13000 Y CUOTAS ⚠️\n \n📍SANTA TERESA ESQUINA VENTURA ALEGRE,  MALDONADO \n📲 096 187 061",
        "fotos":  [
                      "img/autos/007/1.jpg",
                      "img/autos/007/2.jpg",
                      "img/autos/007/3.jpg",
                      "img/autos/007/4.jpg",
                      "img/autos/007/5.jpg",
                      "img/autos/007/6.jpg",
                      "img/autos/007/7.jpg",
                      "img/autos/007/8.jpg",
                      "img/autos/007/9.jpg"
                  ],
        "destacado":  false
    },
    {
        "id":  "008",
        "marca":  "Renault",
        "modelo":  "Oroch",
        "version":  "",
        "anio":  "2018",
        "km":  126000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nRENAULT OROCH 1.6 2018 EXTRA FULL!\n\n- EXTRA FULL\n- AIRE ACONDICIONADO\n- COMANDOS AL VOLANTE \n- DIRECCIÓN HIDRÁULICA \n- FAROS CAMINEROS \n- DOBLE AIRBAG\n- CIERRE CENTRALIZADO \n- MODO ECO \n- LEVANTA VIDRIOS X4\n- 2018\n- 14KM/L EN RUTA\n- SOLO 126.000KM\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN ENTREGANDO DESDE US$10000 Y CUOTAS⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO \n📲 096 187 061",
        "fotos":  [
                      "img/autos/008/1.jpg",
                      "img/autos/008/2.jpg",
                      "img/autos/008/3.jpg",
                      "img/autos/008/4.jpg",
                      "img/autos/008/5.jpg",
                      "img/autos/008/6.jpg",
                      "img/autos/008/7.jpg",
                      "img/autos/008/8.jpg",
                      "img/autos/008/9.jpg"
                  ],
        "destacado":  false
    },
    {
        "id":  "009",
        "marca":  "Renault",
        "modelo":  "Oroch",
        "version":  "Outsider 4x4",
        "anio":  "2023",
        "km":  67000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nRENAULT OROCH OUTSIDER 4X4 2023 UNICO DUEÑO LA MAS FULL DE TODAS  MOTOR 1.3 TURBO!!!\n\n- EXTRA FULL OUTSIDERB4X4\n- AIRE ACONDICIONADO\n- PANTALLA CON APPLE CAR PLAY Y ANDROID AUTO\n- CAMARA DE REVERSA\n- VELOCIDAD CRUCERO\n- COMANDOS AL VOLANTE \n- DIRECCIÓN HIDRÁULICA \n- FAROS CAMINEROS \n- VIDRIOS ELÉCTRICOS\n- DOBLE AIRBAG\n- ALARMA\n- CIERRE CENTRALIZADO \n- MODO ECO \n- LLANTAS DE ALEACIÓN \n- COMANDOS AL VOLANTE\n- LONA MARÍTIMA \n- LEVANTA VIDRIOS X4\n- 2023\n- 15KM/L EN RUTA\n- SOLO 67.000KM\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN ENTREGANDO DESDE US$14000 Y CUOTAS⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO \n📲 096 187 061",
        "fotos":  [
                      "img/autos/009/1.jpg",
                      "img/autos/009/2.jpg",
                      "img/autos/009/3.jpg",
                      "img/autos/009/4.jpg",
                      "img/autos/009/5.jpg",
                      "img/autos/009/6.jpg",
                      "img/autos/009/7.jpg",
                      "img/autos/009/8.jpg",
                      "img/autos/009/9.jpg"
                  ],
        "destacado":  false
    },
    {
        "id":  "010",
        "marca":  "Citroën",
        "modelo":  "C3",
        "version":  "",
        "anio":  "2018",
        "km":  93000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nCITROEN NEW C3 EXTRA FULL 2018 1.2 SUPER ECONÓMICO!!\n\n- AIRE ACONDICIONADO\n- DIRECCIÓN HIDRÁULICA\n- FAROS CAMINEROS \n- MOTOR 1.2 SUPER ECONÓMICO \n- RADIO CON PANTALLA \n- ESPEJOS ELÉCTRICOS\n- COMPUTADORA DE ABORDO\n- VIDRIOS ELÉCTRICOS\n- CIERRE CENTRALIZADO \n- LLANTAS DE ALEACIÓN 15\"\n- COMANDOS AL VOLANTE\n- 2020\n- 93.000KM\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN PROPIA ENTREGANDO DESDE US$9000 Y CUOTAS ⚠️\n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO\n📲 096 187 061",
        "fotos":  [
                      "img/autos/010/1.jpg",
                      "img/autos/010/2.jpg",
                      "img/autos/010/3.jpg",
                      "img/autos/010/4.jpg",
                      "img/autos/010/5.jpg",
                      "img/autos/010/6.jpg",
                      "img/autos/010/7.jpg",
                      "img/autos/010/8.jpg",
                      "img/autos/010/9.jpg"
                  ],
        "destacado":  false
    },
    {
        "id":  "011",
        "marca":  "Renault",
        "modelo":  "Sandero",
        "version":  "Stepway",
        "anio":  "2020",
        "km":  75000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nRENAULT SANDERO STEEPWAY EXTRA FULL 2020 SOLO 75 MIL KM!\n\n* DOBLE AIRBAG\n* FAROS CAMINEROS\n* PANTALLA Y CAMARA\n* ESPEJOS ELECTRICOS\n* AIRE ACONDICIONADO Y CLIMATIZADOR\n* VELOCIDAD CRUCERO\n* DIRECCIÓN HIDRÁULICA \n* VIDRIOS ELÉCTRICOS \n* CIERRE CENTRALIZADO\n* MOTOR 1.6\n* 2020\n* 75.000 KM\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS⚠️\n\n⚠️O FINANCIACIÓN ENTREGANDO DESDE US$8000⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO\n📲 096 187 061",
        "fotos":  [
                      "img/autos/011/1.jpg",
                      "img/autos/011/2.jpg",
                      "img/autos/011/3.jpg",
                      "img/autos/011/4.jpg",
                      "img/autos/011/5.jpg",
                      "img/autos/011/6.jpg",
                      "img/autos/011/7.jpg",
                      "img/autos/011/8.jpg",
                      "img/autos/011/9.jpg"
                  ],
        "destacado":  false
    },
    {
        "id":  "012",
        "marca":  "Volkswagen",
        "modelo":  "Gol",
        "version":  "G6",
        "anio":  "2015",
        "km":  205000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nVOLKSWAGEN GOL G6 1.6 EXTRA FULL TRENDLINE\n\n- AIRE ACONDICIONADO \n- DIRECCIÓN HIDRÁULICA\n- RADIO\n- LLANTAS DE ALEACION Y ABS\n- VIDRIOS ELÉCTRICOS X4\n- DOBLE AIRBAG\n- CIERRE CENTRALIZADO \n- 2015\n- FAROS CAMINEROS \n- 205.000KM!\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN ENTREGANDO DESDE US$7000 Y CUOTAS⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE \n📲 096 187 061",
        "fotos":  [
                      "img/autos/012/1.jpg",
                      "img/autos/012/2.jpg",
                      "img/autos/012/3.jpg",
                      "img/autos/012/4.jpg",
                      "img/autos/012/5.jpg",
                      "img/autos/012/6.jpg",
                      "img/autos/012/7.jpg",
                      "img/autos/012/8.jpg"
                  ],
        "destacado":  false
    },
    {
        "id":  "013",
        "marca":  "Peugeot",
        "modelo":  "207",
        "version":  "Active",
        "anio":  "2012",
        "km":  185000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\nVENDO - PERMUTO - FINANCIO \n\nPEUGEOT 207 ACTIVE HATCH 1.4 \n\n- AIRE ACONDICIONADO\n- TECHO DE VIDRIO PANORÁMICO \n- DIRECCIÓN HIDRÁULICA\n- FAROS CAMINEROS \n- MOTOR 1.4 SUPER ECONÓMICO \n- RADIO\n- ESPEJOS ELÉCTRICOS\n- COMPUTADORA DE ABORDO\n- VIDRIOS ELÉCTRICOS\n- CIERRE CENTRALIZADO \n- LLANTAS DE ALEACIÓN \n- 2012\n- 185.000KM\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN PROPIA ENTREGANDO DESDE US$7000 Y CUOTAS ⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO\n📲 096 187 061",
        "fotos":  [
                      "img/autos/013/1.jpg",
                      "img/autos/013/2.jpg",
                      "img/autos/013/3.jpg",
                      "img/autos/013/4.jpg",
                      "img/autos/013/5.jpg",
                      "img/autos/013/6.jpg",
                      "img/autos/013/7.jpg",
                      "img/autos/013/8.jpg",
                      "img/autos/013/9.jpg"
                  ],
        "destacado":  false
    },
    {
        "id":  "014",
        "marca":  "Kia",
        "modelo":  "Sorento",
        "version":  "",
        "anio":  "2006",
        "km":  278000,
        "combustible":  "Diésel",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nKIA SORENTO 2006 2.5 TURBO DIESEL 4X4\n\n- EXTRA FULL \n- LLANTAS DE ALEACION\n- AIRE ACONDICIONADO \n- DIRECCIÓN HIDRÁULICA \n- FAROS CAMINEROS \n- RADIO CON PANTALA\n- COMPUTADORA DE ABORDO\n- COMANDOS AL VOLANTE\n- VIDRIOS ELÉCTRICOS X4\n- DOBLE AIRBAG\n- ALARMA\n- CIERRE CENTRALIZADO \n- ESPEJOS ELÉCTRICOS\n- 2006\n- 278.000KM\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️ HASTA 100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO Y SIN CLEARING ⚠️\n\n⚠️O FINANCIACIÓN ENTREGANDO DESDE US$8000 Y CUOTAS ⚠️\n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO CENTRO\n📲 096 187 061",
        "fotos":  [
                      "img/autos/014/1.jpg",
                      "img/autos/014/2.jpg",
                      "img/autos/014/3.jpg",
                      "img/autos/014/4.jpg",
                      "img/autos/014/5.jpg",
                      "img/autos/014/6.jpg",
                      "img/autos/014/7.jpg",
                      "img/autos/014/8.jpg",
                      "img/autos/014/9.jpg"
                  ],
        "destacado":  false
    },
    {
        "id":  "015",
        "marca":  "Volkswagen",
        "modelo":  "Bora",
        "version":  "",
        "anio":  "2011",
        "km":  151000,
        "combustible":  "Nafta",
        "caja":  "Manual",
        "color":  "",
        "precio":  "",
        "moneda":  "USD",
        "financiado":  true,
        "anticipo":  "",
        "cuotas":  "60",
        "estado":  "disponible",
        "comentario":  "⚠️ NUEVO INGRESO ⚠️\n\nVENDO - PERMUTO - FINANCIO\n\nVOLKSWAGEN BORA 2.0 2011 EXTRA FULL TECHO Y PANTALLA \n\n- EXTRA FULL\n- TECHO ELÉCTRICO\n- CUERO \n- AIRE ACONDICIONADO \n- DIRECCIÓN HIDRÁULICA \n- PANTALLA \n- VIDRIOS ELÉCTRICOS \n- DOBLE AIRBAG\n- ALARMA \n- CIERRE CENTRALIZADO \n- LLANTAS DE ALEACIÓN\n- 2011\n- 151.000KM\n\n🏁LLÉVALO CON LA FINANCIACIÓN QUE ELIJAS🏁\n\n⚠️100% FINANCIADO HASTA 60 CUOTAS EN PESOS CON RECIBO DE SUELDO ⚠️\n\n⚠️O FINANCIACIÓN ENTREGANDO DESDE US$8000 Y CUOTAS ⚠️ \n\n📍SANTA TERESA ESQUINA VENTURA ALEGRE, MALDONADO.\n📲 096 187 061",
        "fotos":  [
                      "img/autos/015/1.jpg",
                      "img/autos/015/2.jpg",
                      "img/autos/015/3.jpg",
                      "img/autos/015/4.jpg",
                      "img/autos/015/5.jpg",
                      "img/autos/015/6.jpg",
                      "img/autos/015/7.jpg",
                      "img/autos/015/8.jpg"
                  ],
        "destacado":  false
    }
];
